Cleanups

diff --git a/net-fs/autofs/files/autofs5.init b/net-fs/autofs/files/autofs5.init
--- a/net-fs/autofs/files/autofs5.init
+++ b/net-fs/autofs/files/autofs5.init
@@ -1,7 +1,7 @@
 #!/sbin/runscript
-# Copyright 1999-2004 Gentoo Foundation
+# Copyright 1999-2008 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /home/cvs/root/autofs/gentoo/net-fs/autofs/files/autofs.init,v 1.17 2006/03/30 02:09:51 raven Exp $
+# $Header: $
 
 # rc file for automount using a Sun-style "master map".
 # We first look for a local /etc/autofs/auto.master, then a YP
@@ -10,6 +10,7 @@
 DAEMON=/usr/sbin/automount
 SYSCONFDIR=/etc/autofs
 MASTERMAP=$SYSCONFDIR/auto.master
+pidfile=/var/run/autofs.pid
 
 depend() {
 	need localmount	portmap
@@ -29,20 +30,11 @@ start() {
 		exit 1
 	fi
 
-	# ensure pid file directory exists
-	if [ ! -e /var/run/autofs ]
-	then
-		mkdir /var/run/autofs
-	fi
-
 	start-stop-daemon --start --pidfile $pidfile --quiet \
 			--exec $DAEMON -- --pid-file=$pidfile $MASTERMAP
 	ret=$?
 
-	if [ $ret -ne 0 ]
-	then
-		echo "Could not start automount for $mnt"	
-	fi
+	[[ $ret -ne 0 ]] && echo "Could not start automount"
 
 	eend $ret
 }
@@ -50,56 +42,33 @@ start() {
 stop() {
 	ebegin "Stopping automounter"
 
-	for file in `ls /var/run/autofs/*.pid 2>/dev/null`
-	do
-		if [ -e "$file" ]
-		then
-#			any=1
-			pid=`head -n 1 $file`
-			mnt=`ps -wwo 'cmd=' $pid | sed -e \
-			  's,.* --pid-file=/var/run/autofs/\([^ ]*\)\.pid.*,\1,; s,_,/,g'`
-			dname=`basename $DAEMON`
+	dname=`basename $DAEMON`
 
-			start-stop-daemon --stop --quiet \
-					--retry TERM/${daemon_exit_wait} \
-					--pidfile $file --name $dname
-			ret=$?
+	start-stop-daemon --stop --quiet \
+			--retry TERM/5 \
+			--pidfile $pidfile --name $dname
+	ret=$?
 
-			case $ret in
-			0)
-				rm -f $file
-				;;
-			1)
-				echo "No process for automount $mnt"
-				rm -f $file
-				;;
-			2)
-				echo "Couldn't stop automount for $mnt"
-				;;
-			*)
-				echo "Strange start-stop-daemon exit status: $?"
-				;;
-			esac
-		fi
-	done
+	case $ret in
+	0)
+		rm -f $pidfile
+		;;
+	1)
+		echo "No process for automount of pid `cat $pidfile`"
+		rm -f $pidfile
+		;;
+	2)
+		echo "Couldn't stop automount with pid `cat $pidfile`"
+		;;
+	*)
+		echo "Strange start-stop-daemon exit status: $?"
+		;;
+	esac
 
 	eend $ret
 }
 
 reload() {
 	echo "Reloading automounter maps"
-
-	for i in `ls /var/run/autofs/*.pid 2>/dev/null`
-	do
-		pid=`head -n 1 $i 2>/dev/null`
-		[ "$pid" = "" ] && continue
-
-		kill -HUP $pid 2> /dev/null
-	done
+	kill -HUP `cat $pidfile`
 }
-
-restart() {
-	svc_stop
-	svc_start
-}
-
